modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Lykrast/Glassential/issues"
license="MIT License https://github.com/Lykrast/Glassential/blob/master/LICENSE"

[[mods]]
modId="glassential"
version="${file.jarVersion}"
displayName="Glassential"
displayURL="https://modrinth.com/mod/glassential"
logoFile="logo.png"
credits="Extra Utilities 2 for the inspiration, MayusYT for the name, Wouter for the awesome logo, UpcraftLP for the Fabric maintain."
authors="Lykrast"
description='''
Various glasses for all your decorative needs.
'''

[[dependencies.glassential]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.glassential]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,]"
    ordering="NONE"
    side="BOTH"